services:
    innmind_event_bus.default:
        class: Innmind\EventBusBundle\ContainerAwareEventBus
        arguments:
            - '@service_container'
            - []
            - '@innmind_event_bus.class_name.composite_extractor'
        factory:
            - Innmind\EventBusBundle\Factory\ContainerAwareEventBusFactory
            - make
        tags:
            - { name: innmind_event_bus, alias: default }

    innmind_event_bus.queue:
        class: Innmind\EventBus\QueueableEventBus
        arguments:
            - ~
        tags:
            - { name: innmind_event_bus, alias: queue }

    innmind_event_bus.class_name.inheritance_extractor:
        class: Innmind\EventBus\ClassName\InheritanceExtractor
        public: false

    innmind_event_bus.class_name.wildcard_extractor:
        class: Innmind\EventBus\ClassName\WildcardExtractor
        public: false

    innmind_event_bus.class_name.composite_extractor:
        class: Innmind\EventBus\ClassName\CompositeExtractor
        public: false
        arguments:
            - '@innmind_event_bus.class_name.inheritance_extractor'
            - '@innmind_event_bus.class_name.wildcard_extractor'
