services:
    innmind_event_bus.default:
        class: Innmind\EventBusBundle\ContainerAwareEventBus
        arguments:
            - '@service_container'
            - []
        factory:
            - Innmind\EventBusBundle\Factory\ContainerAwareEventBusFactory
            - make
